import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const htmlPath = join(root, 'public', 'index.html')
const outPath = join(root, 'server', 'utils', 'ui-html.ts')

const html = readFileSync(htmlPath, 'utf8')
mkdirSync(dirname(outPath), { recursive: true })
writeFileSync(
  outPath,
  `/* Auto-generated by scripts/embed-ui.mjs — do not edit */\nexport const INDEX_HTML = ${JSON.stringify(html)}\n`,
  'utf8',
)
console.log(`embedded UI html -> ${outPath} (${html.length} chars)`)
